name: Generate Snake
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Azim04
          outputs: |
            ./dist/github-snake.svg
            ./dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          repository: Azim04/Azim04
          target_branch: output
          build_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
